import type { Metadata } from "next";
import "./globals.css";
import { HeroUIProvider } from "@heroui/system";
import Header from "@/components/Layout/Header/Header";
import Footer from "@/components/Layout/Footer/Footer";
import SocialLinks from "@/components/Layout/SocialLinks/SocialLinks";
import Image from "next/image";
import { geistSans } from "@/fonts/geistSans";
import { geistMono } from "@/fonts/geistMono";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--background)] text-[var(--text)] relative`}
      >
        <Image
          src={"/lines.png"}
          width={1920}
          height={1080}
          className="absolute h-full z-[1] opacity-50"
          alt="Паттерн"
        />
        <Header />
        <main className="container mx-auto px-4 relative z-20">
          <HeroUIProvider>{children}</HeroUIProvider>
        </main>
        <SocialLinks />
        <Footer />
      </body>
    </html>
  );
}
